
#define TREASURE_BOMBS      0x02
#define TREASURE_SHIELD     0x04
#define TREASURE_BOW        0x05
#define TREASURE_MAGIC_ROD  0x07
#define TREASURE_FEATHER    0x0A
#define TREASURE_POWDER     0x0C
#define TREASURE_BOOMERANG  0x0D

#define TREASURE_PIECE_OF_POWER  0x0E
#define TREASURE_POTION_1        0x0F
#define TREASURE_POTION_2        0x10
#define TREASURE_MAP             0x11
#define TREASURE_COMPASS         0x12

#define TREASURE_RUPEES_20  0x80
#define TREASURE_RUPEES_50  0x81
#define TREASURE_RUPEES_100 0x82
#define TREASURE_RUPEES_200 0x83
#define TREASURE_SMALL_KEY  0x84

#define TREASURE_PIECE_OF_HEART  0xC0
#define TREASURE_HEART_CONTAINER 0xC1
#define TREASURE_SPIN_POWERUP    0xC2
